server:
  port: 8888
  
spring:
  application:
    name: nascar-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/josecarlosnascimento/nascar-config-server
          default-label: main
          search-paths:
          - 'greeting-service*'
