name: Continuous Integration with Github

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
  
      - name: Setup Java JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build Eurka Naming Server Container Image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API Gateway Server Container Image
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Cambio Microsservice JAR
        working-directory: ./cambio-service
        run: mvn clean package -DskipTests

      - name: Build Book Microsservice JAR
        working-directory: ./book-service
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build
        working-directory: .
        run: docker-compose build
